var OK, READY, sendMsg, update, nickname;

OK = 200;

READY = 4;

init = function() {
  while (true) {
    nickname = prompt("Enter a nickname");
    if (nickname != "") {
      break;
    }
  }
  setInterval(update, 3000);
};

sendMsg = function() {
  var msg, xmlhttp;
  msg = document.getElementById("message").value;
  xmlhttp = new XMLHttpRequest();
  xmlhttp.open("POST", "submit.php", true);
  xmlhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
  xmlhttp.send("nickname=" + nickname + "&message=" + msg);
  document.getElementById("message").value = "";
  update();
};

update = function() {
  var xmlhttp;
  xmlhttp = new XMLHttpRequest();
  xmlhttp.onreadystatechange = function() {
    if (this.readyState === READY & this.status === OK) {
      document.getElementById("chat").innerHTML = this.responseText;
    }
  };
  xmlhttp.open("GET", "read.php", true);
  xmlhttp.send();
};

checkKeyEvents = function(event) {
  if (event.key == "Enter") {
    sendMsg();
  }
};

// ---
// generated by coffee-script 1.9.2