var OK, READY, sendMsg, update, nickname;

OK = 200;

READY = 4;

init = function() {
  nickname = prompt("Enter a nickname");
  setInterval(update, 3000);
};

sendMsg = function() {
  var msg, xmlhttp;
  msg = document.getElementById("message").value;
  xmlhttp = new XMLHttpRequest();
  xmlhttp.onreadystatechange = function() {
    if (this.readyState === READY & this.status === OK) {
      alert(this.responseText);
    }
  };
  xmlhttp.open("POST", "submit.php", true);
  xmlhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
  xmlhttp.send("nickname=" + nickname + "&message=" + msg);
};

update = function() {
  var xmlhttp;
  xmlhttp = new XMLHttpRequest();
  xmlhttp.onreadystatechange = function() {
    if (this.readyState === READY & this.status === OK) {
      document.getElementById("chat").innerHTML = this.responseText;
    }
  };
  xmlhttp.open("GET", "read.php", true);
  xmlhttp.send();
};

// ---
// generated by coffee-script 1.9.2